# Generated by Django 5.0.4 on 2024-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='im',
            field=models.ImageField(default='', upload_to='files'),
        ),
    ]
