# Generated by Django 5.0.4 on 2024-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
    ]
