# Generated by Django 5.0.4 on 2024-08-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_resume_im'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='im',
        ),
    ]
